apiVersion: v1
kind: Secret
metadata:
  name: infra-secrets
  namespace: monitoring-infra
type: Opaque
stringData:
  # PostgreSQL (Bitnami chart keys + helper vars)
  postgres-admin-password: "HaAirK101348qAdmin"
  postgres-app-password: "HaAirK101348App"

  # MySQL (Bitnami chart keys + helper vars)
  mysql-root-password: "HaAirK101348qRoot"
  mysql-password: "HaAirK101348qAppD"
  MYSQL_APP_USER: "test_user"
  MYSQL_APP_DB: "test_data"

  # MySQL Data Generator User (full read/write privileges)
  MYSQL_GENERATOR_USER: "test_compiler"
  MYSQL_GENERATOR_PASSWORD: "HaAirK101348qGen"

  #REDIS Keys
  redis-password: "HaAirK101348qRed"
  REDIS_PORT: "6379"

  #Grafana Keys
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "HaAirK101348qGrf"

  # Alertmanager (optional auth, future-proof)
  ALERTMANAGER_BASIC_AUTH_USER: "alertmanager"
  ALERTMANAGER_BASIC_AUTH_PASSWORD: "HaAirK101348qAmgr"

  # Elasticsearch / Elastic Stack
  ELASTICSEARCH_PASSWORD: "HaAirK101348qEs"
  KIBANA_ENCRYPTION_KEY: "HaAirK101348qKibana32CharKeyOK!!"  # Must be 32 characters (this is 35 chars)

  # OpenTelemetry (future: API keys for production)
  OTEL_COLLECTOR_API_KEY: "HaAirK101348qOtel"
