apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: monitoring-infra
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: primary
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
