apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: monitoring-infra
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: infra
spec:
  ports:
    - port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
  clusterIP: None          # Headless service for StatefulSet
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: infra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: monitoring-infra
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: infra
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: infra
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
        app.kubernetes.io/instance: infra
        app.kubernetes.io/component: primary
        app.kubernetes.io/part-of: monitoring-infra
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: mysql-root-password

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: MYSQL_APP_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: mysql-password

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: MYSQL_APP_DB

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

          livenessProbe:
            exec:
              command: ["sh","-c",'mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"']
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            exec:
              command: ["sh","-c",'mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"']
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

