apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: monitoring-infra
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: master
    app.kubernetes.io/part-of: monitoring-infra
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: master
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30379
